version: "3"
services:
  web:
    build: .
    ports: ['5000:5000']
    environment:
      - HF_HOME=/huggingface
    volumes: [
      '.:/app',
      '/home/ubuntu/.cache/huggingface:/huggingface'
    ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
